<h3>Add new user</h3>
<hr>
<form action="" method="post">
    <div class="form-group">
        <label for="name">Business name</label>
        <input type="text" name="businessName" class="form-control" id="name" placeholder="Business name" value="<?php echo $this->user->businessName; ?>">
    </div>
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" name="email" class="form-control" id="email" placeholder="Email" value="<?php echo $this->user->email; ?>">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" class="form-control" id="password" placeholder="New password">
    </div>
    <button type="submit" class="btn btn-default">Save</button>
</form>